version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/codedeploy
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ec2-user/codedeploy
    owner: ec2-user
    group: ec2-user
    mode: 755

